Refactor ocrpdf
Summary:
  * Prefix function with `function`.
  * Declare globals
  * Add pipefail

diff --git a/bin/ocrpdf b/bin/ocrpdf
--- a/bin/ocrpdf
+++ b/bin/ocrpdf
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ## ----------------------------------------------------------------------------
 ## A utility to run a scanned PDF through tesseract's OCR engine and make it
@@ -14,32 +14,36 @@
 ## -----------------------------------------------------------------------------
 ## Settings
 ## -----------------------------------------------------------------------------
-trap cleanup EXIT
 set -o nounset
 set -o errexit
+set -o pipefail
+
+trap cleanup EXIT
 
 ## -----------------------------------------------------------------------------
 ## GLOBALS
 ## -----------------------------------------------------------------------------
-VERSION=0.2
-SCRIPT=${0##*/}
-DEPENDENCIES=(
+declare -r SCRIPT=${0##*/}
+declare -r VERSION=0.2.1
+declare -r AUTHOR="Urs Roesch <github@bun.ch>"
+declare -r LICENSE="MIT"
+declare -a PDF_FILES=()
+declare -a INCLUDES=(
+  pdfcat
+)
+declare -a DEPENDENCIES=(
   pdfcat
   pdfimages
   pdftk
   tesseract
 )
-INCLUDES=(
-  pdfcat
-)
-PDF_FILES=()
 
 ## -----------------------------------------------------------------------------
 ## FUNCTIONS
 ## -----------------------------------------------------------------------------
 
-check_dependencies() {
-  for dependency in ${DEPENDENCIES[*]}; do
+function check_dependencies() {
+  for dependency in ${DEPENDENCIES[@]}; do
     if ! which ${dependency} >/dev/null 2>&1; then
       echo "Missing dependency '${dependency}'" 1>&2
       echo "Please install first!" 1>&2
@@ -50,8 +54,8 @@ check_dependencies() {
 
 ## -----------------------------------------------------------------------------
 
-source_includes() {
-  for include in ${INCLUDES[*]}; do
+function source_includes() {
+  for include in ${INCLUDES[@]}; do
     local path=$( which ${include} 2>/dev/null )
     [[ -n ${path} ]] && source ${path}
   done
@@ -59,7 +63,7 @@ source_includes() {
 
 ## -----------------------------------------------------------------------------
 
-set_ocr_language() {
+function determine_ocr_languages() {
   OCR_LANG=$(
     sed 's/ /+/g' <<< $( echo $( tesseract --list-langs 2>&1 | grep "^...$" ) )
   )
@@ -67,28 +71,30 @@ set_ocr_language() {
 
 ## -----------------------------------------------------------------------------
 
-run_ocr() {
-  local filename="$1"; shift;
+function run_ocr() {
+  local filename="${1}"; shift;
   tesseract -l ${OCR_LANG} "${filename}" "${filename%%.*}" pdf >/dev/null 2>&1
   if [[ $? -eq 0 ]]; then
     rm "${filename}"
   else
-    echo "An error occured during character recogntion" 1>&2
-    echo "Please chech leaving original image '${filename}' intact" 1>&2
+    echo "An error occured during character recogntion." 1>&2
+    echo "Please investigate!" 1>&2
+    echo "Leaving original image '${filename}' intact" 1>&2
     exit 128
   fi
 }
 
 ## -----------------------------------------------------------------------------
 
-print_version() {
-  echo ${SCRIPT} version ${VERSION}
+function version() {
+  printf "%s v%s\nCopyright (c) %s\nLicense - %s\n" \
+    "${SCRIPT}" "${VERSION}" "${AUTHOR}" "${LICENSE}"
   exit 0
 }
 
 ## -----------------------------------------------------------------------------
 
-usage() {
+function usage() {
   local exit_code=$1
   cat <<USAGE
 
@@ -96,11 +102,12 @@ usage() {
     ${SCRIPT} [options] <file> [<file> [,,]]
 
   Options:
-    -h | --help     This message
-    -v | --version  Print version information and exit
-    -l | --lang     Set the OCR language for multiple concatenate with a +
-                    E.g eng+deu for English and German
-                    default: ${OCR_LANG}
+    -h | --help         This message
+    -V | --version      Print version information and exit
+    -l | --lang <lang>  Set the OCR languages to use.
+                        For multiple languages concatenate with a '+'
+                        E.g eng+deu for English and German
+                        Default: ${OCR_LANG}
 
   Description:
     Runs PDFs through OCR and saves the output as a text searchable PDF
@@ -118,24 +125,25 @@ USAGE
 
 ## -----------------------------------------------------------------------------
 
-check_compatible() {
-  local file="$1"; shift;
+function check_compatibility() {
+  local file="${1}"; shift;
   ## check if all the images are single jpegs
-  pdfimages -list "${file}" | awk \
-    '/^ +[0-9]/{p=$1; c++; $9 ~ /^(jpeg|image)$/ && j++ }
-    END { if (p < c && p == j) {exit 1} }'
+  pdfimages -list "${file}" | \
+    awk \
+      '/^ +[0-9]/{p=$1; c++; $9 ~ /^(jpeg|image)$/ && j++ }
+       END { if (p < c && p == j) {exit 1} }'
 }
 
 ## -----------------------------------------------------------------------------
 
-ocr_pdfs() {
+function ocr_pdfs() {
   for file in "${PDF_FILES[@]}"; do
-    if ! check_compatible "${file}"; then
+    if ! check_compatibility "${file}"; then
       echo "${file} is not compatible; skipping!"
       continue
     fi
     workname="$$-${RANDOM}"
-    meta="$( fetch_meta "${file}" )"
+    meta="$(fetch_meta "${file}")"
     pdfimages -all "${file}" "${workname}" 2>/dev/null &&
     for image in ${workname}*; do
       run_ocr ${image}
@@ -146,10 +154,10 @@ ocr_pdfs() {
 
 ## -----------------------------------------------------------------------------
 
-post_process_pdf() {
-  local file="$1"; shift;
-  local workname="$1"; shift;
-  local meta="$1"; shift;
+function post_process_pdf() {
+  local file="${1}"; shift;
+  local workname="${1}"; shift;
+  local meta="${1}"; shift;
   merge_pdf "${workname}.pdf" ${workname}*
   pdftk "${workname}.pdf" \
     update_info_utf8 <( echo "${meta}" ) \
@@ -159,9 +167,9 @@ post_process_pdf() {
 
 ## -----------------------------------------------------------------------------
 
-merge_pdf() {
-  local filename="$1"; shift;
-  local documents=( "$@" ); shift;
+function merge_pdf() {
+  local filename="${1}"; shift;
+  local documents=( "${@}" ); shift;
   if [[ ${#documents[@]} -eq 1 ]]; then
     mv "${documents[0]}" "${filename}" 2>/dev/null
   else
@@ -172,13 +180,14 @@ merge_pdf() {
 
 ## -----------------------------------------------------------------------------
 
-parse_opts() {
-  while [[ $# -gt 0 ]]; do
-    case $1 in
-      -v|--version) print_version;;
-      -l|--lang)    shift; OCR_LANG=$1;;
-      -h|--help)    usage 0;;
-      *)            PDF_FILES=( "${PDF_FILES[@]}" "$1" );;
+function parse_options() {
+ [[ ${#} -lt 1 ]] && usage 1
+  while [[ ${#} -gt 0 ]]; do
+    case ${1} in
+    -V|--version) version;;
+    -l|--lang)    shift; OCR_LANG=${1};;
+    -h|--help)    usage 0;;
+    *)            PDF_FILES=( "${PDF_FILES[@]}" "${1}" );;
     esac
     shift
   done
@@ -186,7 +195,7 @@ parse_opts() {
 
 ## -----------------------------------------------------------------------------
 
-cleanup() {
+function cleanup() {
   rm $$-[0-9]*.{jpg,pdf} 2>/dev/null
 }
 
@@ -195,6 +204,6 @@ cleanup() {
 ## -----------------------------------------------------------------------------
 check_dependencies
 source_includes
-set_ocr_language
-parse_opts "$@"
+determine_ocr_languages
+parse_options "${@}"
 ocr_pdfs
